[package]
name = "redox_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = {workspace = true}
crossterm = {workspace = true, features = ["bracketed-paste", "windows", "events", "event-stream"]}
ratatui = {workspace = true, features = ["crossterm", "underline-color", "unstable-widget-ref"]}
tokio = {workspace = true, features = ["macros", "signal"]}
tracing = {workspace = true}
tui-realm-stdlib = "1.3.2"
tuirealm = "1.9.2"
