[package]
name = "redox_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = {workspace = true}
chrono = { workspace = true }
iocraft = "0.3.2"
redox_api={workspace = true}
redox_core={workspace = true}
tokio = { workspace = true }
tracing = {workspace = true}
