Output "static/demo.gif"
Set Width 1200
Set Height 800
Set FontSize 18
Set Framerate 24
Set Margin 0
Set Padding 10
Set Theme "Catppuccin Mocha"

Hide
Type "cargo build --release"
Enter
Sleep 2s
Type "cp target/release/redox_commander ~/bin"
Enter
Type "clear"
Enter
Show

Type@75ms "redox_commander"
Enter
Sleep 1s
Type "d"
Sleep 2s
Type "o"
Sleep 2s
Type "e"
Sleep 2s

Hide
Type "q"
Type "clear"
Enter

Show
Sleep 1s
