Output "static/demo.gif"
Set Width 1200
Set Height 800
Set FontSize 18
Set Framerate 24
Set Margin 0
Set Padding 10
Set Theme "Catppuccin Mocha"

Hide
Type "cargo build --release"
Enter
Sleep 2s
Type "cp target/release/rc ~/bin"
Enter
Type "clear"
Enter
Show

Sleep 500ms
Type@75ms "rc"
Sleep 700ms
Enter
Sleep 1500ms
Type "d"
Sleep 1500ms
Type "o"
Sleep 1500ms
Type "e"
Sleep 1500ms
Type "R"
Sleep 2s

Hide
Type "q"
Type "clear"
Enter

Show
Sleep 1s
