[package]
name = "redox_tui2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = {workspace = true}
chrono = { workspace = true }
iocraft = "0.3.2"
smol = "2.0.1"
tracing = {workspace = true}
